# Generated by Django 6.1.1 on 2026-09-17 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(db_index=True, help_text='Unique student registration/roll number (e.g., 25AD3018)', max_length=20, unique=True, verbose_name='Register Number')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(help_text='10-digit mobile number', max_length=15, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, verbose_name='Gender')),
                ('department', models.CharField(choices=[('AI&DS', 'Artificial Intelligence & Data Science'), ('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], default='AI&DS', max_length=50, verbose_name='Department')),
                ('year', models.CharField(choices=[('I', '1st Year (I)'), ('II', '2nd Year (II)'), ('III', '3rd Year (III)'), ('IV', '4th Year (IV)')], default='I', max_length=5, verbose_name='Year')),
                ('section', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], default='A', max_length=5, verbose_name='Section')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('admission_date', models.DateField(default=django.utils.timezone.now, verbose_name='Admission Date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
